/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// This code is for Discovery Board
#define RCC_BASE_ADDRESS		0x40023800UL
#define RCC_CFGR_REG_OFFSET		0x08UL

#define RCC_CR_REG_OFFSET		0x00UL

#define RCC_CFGR_REG_ADDRESS	(RCC_BASE_ADDRESS + RCC_CFGR_REG_OFFSET)

#define RCC_CR_REG_ADDRESS		(RCC_BASE_ADDRESS + RCC_CR_REG_OFFSET)


int main(void)
{
	uint32_t *pRccCrReg = (uint32_t*)RCC_CR_REG_ADDRESS;

	// 1. Enable the HSE clock using HSEON bit (RCC_CR)
	*pRccCrReg |= (1 << 16);

	// 2. Wait until HSE clock from the external crystal stabilizes (only if crystal is connected)
	while(!(*pRccCrReg & (1 << 17)));

	// 3. Switch the system clock to HSE (RCC_CFGR)
	uint32_t *pRccCfgrReg = (uint32_t*)RCC_CFGR_REG_ADDRESS;

	*pRccCfgrReg |= (1 << 0);
	*pRccCfgrReg &= (0 << 1);

	// 4. Do MCO1 settings to measure it
	*pRccCfgrReg &= (0 << 21);	// clear bit 21
	*pRccCfgrReg |= (1 << 22);	// set bit 22

	// Configure MCO1 prescaler: divisor as 4
	*pRccCfgrReg |= (1 << 26);
	*pRccCfgrReg |= (1 << 25);
	*pRccCfgrReg &= (0 << 24);

	// continue ...

    /* Loop forever */
	for(;;);
}

void I2C1_EV_IRQHandler(void)
{

}
