/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define RCC_BASE_ADDRESS		0x40023800UL
#define RCC_CFGR_REG_OFFSET		0x08UL
#define RCC_CFGR_REG_ADDRESS	(RCC_BASE_ADDRESS + RCC_CFGR_REG_OFFSET)

#define GPIOA_BASE_ADDRESS		0x40020000UL

int main(void)
{
	// 1. Configure the RCC_CFGR register
	uint32_t *pRccCfgrReg = (uint32_t*)RCC_CFGR_REG_ADDRESS;

	*pRccCfgrReg = (0 << 21);	// clear bit 21
	*pRccCfgrReg = (0 << 22);	// clear bit 22

	// Configure MCO1 prescaler
	*pRccCfgrReg |= (1 << 26);
	*pRccCfgrReg |= (1 << 25);
	*pRccCfgrReg &= (0 << 24);

	// 2. Configure PA8 to AF0 mode to behave as MCO1 signal
	// a) Enable the peripheral clock for GPIOA peripheral
	uint32_t *pRccAhb1Enr = (uint32_t*)(RCC_BASE_ADDRESS + 0x30);
	*pRccAhb1Enr |= (1 << 0);	// Enable GPIOA peripheral clock

	// b) Configure the mode of GPIOA pin 8 as alternate function mode
	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDRESS + 0x00);



    /* Loop forever */
	for(;;);
}
