/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// This is string literal (constant data). This will be stored in ROM (Flash memory)
const char *pMessage = "Hi there, Good Morning!";

// This is constant data. This data also will be stored in ROM (Flash Memory)
const int value = 200;

// This is not a constant data. This will be stored in SRAM
char myData[50];

int main(void)
{
	for(uint32_t i = 0; i < strlen(pMessage); i++)
	{
		// This is data copy from FLASH to SRAM
		myData[i] = *(pMessage + i);
	}
    /* Loop forever */
	for(;;);
}
